spring:
  cloud:
    gateway:
      routes:

        - id: easy-on-board
          uri: lb://EASY-ON-BOARD
          predicates:
            - Path=/eob/onboarding/**

        - id: easy-on-board
          uri: lb://EASY-ON-BOARD
          predicates:
            - Path=/eob/account/**
          filters:
            - AuthenticationFilter

        - id: meta-data-service
          uri: lb://META-DATA-SERVICE
          predicates:
            - Path=/meta/**
          filters:
            - AuthenticationFilter

        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**